---
title: "Antimicrobial Genes"
author: "Rebecca M. Grimwood"
date: "17/08/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Import libraries
```{r libraries, message=FALSE, warning=FALSE}

library(reshape2)
library(RColorBrewer)
library(ggplot2)
library(vegan)

pen_names = c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10", "V12", "V13", "V14", "V15", "K191B1", "K191C", "K191A", "K191C1", "K191C5", "R193B1", "R193B2", "WAI1", "WAI2", "WAI3", "WAI4", "WAI5", "WAI6", "WAI7", "WAI8", "WAI9", "WAI10")

```

## Antimicrobial Resistance Genes
```{r antimicrobials}

# Read in AMR gene standardised abundances
amr_genes = read.csv("Data/amr_genes_standardised_2021.csv", sep=",", header=T, row.names = 1)
colnames(amr_genes) = pen_names

# Convert to PA
amr_pa = amr_genes>0
amr_pa = amr_pa*1

# PA of AMR genes/sample
t_amr = t(amr_pa)

# PA map/graph
# Cluster columns
amr.pa.col = vegdist(t(t_amr), method = "bray")
amr.col.clus = hclust(amr.pa.col, "aver")

# Cluster rows
amr.pa.rows = vegdist(t_amr, method = "bray")
amr.row.clus = hclust(amr.pa.rows, "aver")

heatmap(as.matrix(t_amr), Rowv = as.dendrogram(amr.row.clus), Colv = as.dendrogram(amr.col.clus), margins = c(3, 3), col=c("light grey", "light blue"))



# Normalise by sample
t_amr = t(amr_genes)
t_amr_norm = sweep(t_amr,1,colSums(t_amr),"/")

# Make colour object
colour = colorRampPalette(brewer.pal(8, "RdBu"))(10)

# Cluster columns
amr.dist.col = vegdist(t(t_amr_norm), method = "bray")
amr.clus.col = hclust(amr.dist.col, "aver")

# Cluster rows
amr.dist.row = vegdist(t_amr_norm, method = "bray")
amr.clus.row = hclust(amr.dist.row, "aver")

# Plot
heatmap(as.matrix(t_amr_norm), col=rev(colour), Rowv = as.dendrogram(amr.clus.row), 
        Colv = as.dendrogram(amr.clus.col),  margins = c(10, 3))


# Barplot
t_amr_norm = sweep(t_amr,1,rowSums(t_amr),"/")
rowSums(t_amr_norm)
melted_amr = melt(t_amr)
colnames(melted_amr) = c("Sample", "AM", "Standardised Abundance")
bp = ggplot(melted_amr, aes(fill=AM, y=`Standardised Abundance`, x=Sample)) + 
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) 

colour = colorRampPalette(brewer.pal(8, "RdBu"))(50)
bp + scale_fill_brewer(palette="Greens")


```
